# POST  http://localhost:3000/auth/login



# curl -X POST http://localhost:3000/room/createRoom
#  \
# -H "Content-Type: application/json" \
# -d '{
#   "roomName": "Game Room 1",
#   "playerCount": 4,
#   "isPublic": true,
#   "password": null,
#   "owner": {
#     "name":"zld",
#     "avatar":"null",
#     "user_rank":"null"
#   },
#   "players": []
# }'


POST  http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "account": "root",
    "password": "12323"
}
###
```json
{
  "code": 200,
  "data": {
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiYWNjb3VudCI6InJvb3QiLCJpYXQiOjE3NTI0ODQ0MzksImV4cCI6MTc1MjkxNjQzOX0.OdWDJYO6IdPFpEueQPaNuvrd5ivOJz8c84jpMRXvhmg",
    "user": {
      "id": 2,
      "account": "root",
      "name": "root",
      "permissions": []
    }
  }
}
or
{
  "message": "找不到用户",
  "code": 401
}
```
###
POST  http://localhost:3001/auth/register HTTP/1.1
content-type: application/json

{
    "account": "root",
    "password": "123123",
    "name":"root"
}

###
Get http://localhost:3001/user/all HTTP/1.1